### ISSUE TITLE
transaction_details.gross_amount is required","transaction_details.gross_amount is not a number","transaction_details.order_id is required

### ISSUE THREAD

**Issue by ajieno** [rizdaprasetya/midtrans-mobile-merchant-server--php-sample-#10]
###  I have problem with android integration, when i using sample in postman it's work, but when i using it from android it sho this error, can anybody tell this solution, thankyou

D/OkHttp: --> POST https://pokkiproject.com/charge
    Content-Type: application/json
    Content-Length: 271
    Accept: application/json
D/OkHttp: {"customer_details":{"customer_identifier":"mail@mail.com","email":"mail@mail.com","first_name":"user fullname","phone":"085310102020"},"item_details":[],"transaction_details":{"currency":"IDR","gross_amount":28000.0,"order_id":"1617873344071"},"user_id":"mail@mail.com"}
    --> END POST (271-byte body)
D/OkHttp: <-- 400 https://pokkiproject.com/charge/ (1586ms)
    date: Thu, 08 Apr 2021 09:17:41 GMT
    server: Apache
    vary: Accept-Encoding
    content-type: application/json
D/OkHttp: {"error_messages":["transaction_details.gross_amount is required","transaction_details.gross_amount is not a number","transaction_details.order_id is required"]}
    <-- END HTTP (161-byte body)
E/PaymentMethodsActivity: checkout>error:Failed to retrieve response from server

**Comment by rizdaprasetya** [comment]
hi @ajieno looks like because your backend did some unwanted redirect that you didn't realize:
Any request coming to `https://pokkiproject.com/charge` your backend will auto redirect it as GET request with empty body to `https://pokkiproject.com/charge/` (your backend added `/` at the end of URL during the redirect).

The GET redirect removed the original POST request Body. So that is causing the issue.

You will need to figure out (according to your server/backend/infra config) how your backend implementation should respond directly to request in `https://pokkiproject.com/charge` and should not do any redirection. As that is specific to server/backend/infra configuration, we are not specifically able to help with that.

Also since this is not official Midtrans channel for asking question, it is recommended to contact Midtrans Support email for proper replies. Thanks
