### ISSUE TITLE
[Sandbox] Error base URL setup

### ISSUE THREAD

**Issue by alann-maulana** [rizdaprasetya/midtrans-mobile-merchant-server--php-sample-#3]
Error base URL setup using `/charge/index.php`, showing error :
```
Content-Type: application/json
Server: - Web acceleration by http://www.unixy.net/varnish
X-Cacheable: YES
Accept-Ranges: bytes
Date: Mon, 06 Aug 2018 03:13:04 GMT
X-Varnish: 1704966374 1704966368
Via: 1.1 varnish
Connection: keep-alive
Vary: Accept-Encoding,User-Agent, User-Agent
age: 0
X-Cache: HIT
X-Cache-Hits: 1
{
    "error_messages": [
        "transaction_details.gross_amount is required",
        "transaction_details.gross_amount is not a number",
        "transaction_details.order_id is required"
    ]
}
```

The correct base url uses `/charge` only.

**Comment by rizdaprasetya** [comment]
Hi @alann-maulana 

Based on the error message:
```
{
    "error_messages": [
        "transaction_details.gross_amount is required",
        "transaction_details.gross_amount is not a number",
        "transaction_details.order_id is required"
    ]
}
```
This is caused by `null` value on `gross_amount`, and `order_id`.
Can be because: 

A) you were sending null value, or 
B) your server **do some redirect**, while the redirect can **cause the JSON body being removed**. 

This behavior depends on the web-server/proxy/redirect-rule being used on the hosted server. And I can't control web-server being used.

On the readme, I put `/charge/index.php` to ensure every web server will be able to route the request to the `/charge/index.php` file. Because not all web server able to handle `/charge` being routed to an `index.php` file. 
Using `/charge/index.php` can have consequences, that can cause issue **B**. That is maybe what happen on your case.

If your server works with just `/charge` then no need to use `/charge/index.php`.

Thanks for giving feedback.
I'll try to figure out what url is able to be routed properly for most web server. Or if you have any idea, we can discuss here.
